### PR TITLE
Qrda cat 1

### PR DESCRIPTION
**Pull request by adunsulag**
Implemented the Date, View, Cat1View, Frequency, PatientView, and EntityHelper mustache helper classes. 

Changed the mustache library to be the openemr mustache library that injects the Context into the mustache template helper functions (on both lambda's and object methods).

I implemented but was unsure if the data format is correct for the following helper methods that we'll want to look closely at
PatientView->mrn()
Cat1View->result_value_as_string()
View->measures()

The following methods are still outstanding to be implemented.
Cat1View->get_code_system_for_oid()
Cat1->patient_care_experience()
Cat1->provider_care_experience()

### CODE REVIEW

**Comment by adunsulag** [comment]
@kchapple Here are my updates.

**Comment by sjpadgett** [comment]
Looks like we're passing in some standard classes in patient data. Expects arrays. prevalencePeriod is example.

**Comment by kchapple** [comment]
Thanks @adunsulag

**Comment by sjpadgett** [comment]
@kchapple @adunsulag  I have some fixes that you'll need dealing with stdClass to arrays and handling null values to value_or_null_flavor().
Also I need to refactor some templates to deal with sections e.g #{result['value']} should be {#result['value']} though, I don't understand why ruby would be different in this regard or am I wrong!

will push PR soon. At least the document is rendering al the way through. 
Also I need to add a lookup for system for given oids in our code service.

**Pull request merged**
