### PR TITLE
1. fixed output date according with format, which configured in OpenE…

### PR DESCRIPTION
**Pull request by ratkus91**
…MR Global Administration

2. exchange old datetimepicker to new jquery plugin

### CODE REVIEW

**Comment by growlingflea** [comment]
Good job squashing, but there are still conflicts with master.  Please remember to update you master branch and rebase your braches with master to keep the flow of changes constant.  

Thanks!!!

Please see stash if you have any questions.

**Comment by growlingflea** [comment]
Please remember, when squashing you need to delete the remote branch before pushing the squashed branch.

**Comment by growlingflea** [comment]
There are still conflicts.  PLease resolve.

**Comment by growlingflea** [comment]
There are still conflicts on this branch, please resolve.

**Comment by Leo24** [comment]
Conflicts resoleved and pushed to new branch https://github.com/mi-squared/openemr/pull/21

**Pull request closed without merging**
