### PR TITLE
Issue 4469

### PR DESCRIPTION
**Pull request by kchapple**
Fixes #

### CODE REVIEW

**Comment by kchapple** [comment]
Hi @StuartSmith183 Code looks good (except some very minor style/lint things). The event type isn't showing up in the system log viewer (Administration > System > Log) maybe you need to add 'patient-merge' to the list? Not sure.

Screen Shot 2021-06-23 at 11 28 38 AM

**Comment by StuartSmith183** [comment]
Oh yeah... meant to mention that! It gets those lists via a select from the audit log itself. So once _any_ tag is actually in the audit log, it should show up in the drop down.

**Comment by kchapple** [comment]
I think I see the issue. In the main function (at around like 304) where they loop through the tables there are calls to updateRows() and deleteRows() as well as mergeRows(). You only added logging to the merge operation. You could add log calls to all those functions, or consolidate those to one function modifyRows('delete'), modifyRows('merge'), modifyRows('update') and then call your log and then call the underlying function. The main patient model operation is a 'delete' operation. They just delete the duplicate and don't try to merge the record.

**Comment by StuartSmith183** [comment]
Well, dang... you're right... somehow I missed or mis-read that as not 'belonging' to the merge stuff... I'll correct and get a patch in a bit.

**Comment by kchapple** [comment]
No prob! Can’t “assume” anything with openemr, except that what the code “looks like it’s doing” and what it’s “actually doing” are totally different. 🤣🤣🤣 Let me know if you need help spinning up the OpenEMR locally, or want help with debugger setup.

**Comment by kchapple** [comment]
I am seeing an error in the PHP error log:
`Fatal error:  Uncaught Error: Class 'EventAuditLogger' not found in /Users/kchapple/Dev/www/openemr/master/interface/patient_file/merge_patients.php:196`
You need to put a 'use' statement in the top of the PHP file to indicate to the autoloader to bring the class into scope. The result is that the program crashes and the source patient isn't deleted because it crashes out on the first time the logMergeEvent() method is called. 

For a functional test of this feature, you should create two patients (click Patient/Client > Patients > + Add New Patient). The DOB's must match or else the merge won't start. It's helpful to name them both "Test-something" so you can find them in the merge tool by searching the name "test". Once you have two patients, go to the merge tool and run your merge, selecting the source and target patients. 

Then go to the audit log (click Administration > System > log) and make sure that you can filter on 'patient-merge' events. 

Thanks!

**Comment by StuartSmith183** [comment]
Oh good grief ... I'm almost positive that  I'd added the 'use' in when I
first started down this path... I must have accidentally removed it during
a re-factor.  Odd that the IDE didn't catch that.

S. Stuart Smith

**Comment by kchapple** [comment]
This is great. Just maybe change the event name to 'patient-merge' rather than 'patient_merge' to match the convention. 

And maybe fix the lint errors that the CI spit out (let me know if you have any questions about these.) 

Once that's done, we can squash this into one commit and create a pull request to the upsteam OpenEMR. I can help if you're not sure how to do that.

Thanks, nice work!

```
FILE: /home/runner/work/openemr/openemr/interface/patient_file/merge_patients.php
---------------------------------------------------------------------------------------
FOUND 22 ERRORS AFFECTING 16 LINES
---------------------------------------------------------------------------------------
  81 | ERROR | [x] Expected at least 1 space before "."; 0 found
  99 | ERROR | [x] Expected at least 1 space before "."; 0 found
 106 | ERROR | [x] Whitespace found at end of line
 108 | ERROR | [x] Whitespace found at end of line
 113 | ERROR | [x] Whitespace found at end of line
 146 | ERROR | [x] Expected at least 1 space before "."; 0 found
 146 | ERROR | [x] Expected at least 1 space before "."; 0 found
 148 | ERROR | [x] Expected at least 1 space before "."; 0 found
 159 | ERROR | [x] Expected at least 1 space before "."; 0 found
 159 | ERROR | [x] Expected at least 1 space before "."; 0 found
 160 | ERROR | [x] Expected at least 1 space before "."; 0 found
 167 | ERROR | [x] Whitespace found at end of line
 178 | ERROR | [x] Expected at least 1 space before "."; 0 found
 178 | ERROR | [x] Expected at least 1 space before "."; 0 found
 179 | ERROR | [x] Whitespace found at end of line
 180 | ERROR | [x] Expected at least 1 space before "."; 0 found
 192 | ERROR | [x] Whitespace found at end of line
 198 | ERROR | [x] Only one argument is allowed per line in a multi-line function call
 198 | ERROR | [x] Only one argument is allowed per line in a multi-line function call
 198 | ERROR | [x] Only one argument is allowed per line in a multi-line function call
 198 | ERROR | [x] Whitespace found at end of line
 199 | ERROR | [x] Only one argument is allowed per line in a multi-line function call
```

**Comment by StuartSmith183** [comment]
You didn't see the other commit on that...

patient-merge gets mangled when the query for the event list happens (it
gets turned into 'patient')
I thought about patientMerge or patientmerge etc... patient_merge was the
compromise.
... any ideas on a better 'tag' that would not need any '-' or '_' ??

The lint errors... yeah... those are ALL over the place ...
(Side note ... Irealized that is the reason my IDE is not 'seeing' the
obvious errors (i.e. 'use')... the format warnings are causing so many
errors that it overflows some threshold and causes the IDE to stop
processing the syntax (facepalm). At least now I know, and can deal with
that appropriately.)

I can fix them very easily... I have my IDE setup for auto-formatting to
the language spec... but it reformats the entire file, (which I'm good with
... more people need to do that IMO)... but it does create a pretty big
multi-line change.

Do you want me to do that? or just make sure the lines I added are up to
spec?

I should be able to do the squash and PR - we didn't do squashes at the
last gig, so it has been a while since I've done that, but it should come
back once I look at it.

S. Stuart Smith

**Comment by kchapple** [comment]
Ahh, ok. I wonder how the patient-record and security-administration ones got in there. I'm find with it how it is, but the gatekeepers of the project can be picky, and I was just trying to get ahead of them. I also don't have an opinion on the reformatting the file, but the thing with that (like you said) is that it can a code review tough because the IDE will change every line. I don't really care though, as long as it passes their linter!

**Comment by kchapple** [comment]
You probably DON'T need to squash. You can just create a new PR against the upstream master and they'll squash it when they merge the PR.

**Comment by kchapple** [comment]
I meant "don't need to squash" lol

**Comment by StuartSmith183** [comment]
Ha! Cool.

D'oh ... it trims off the last '-.*' so 'security-administration-insert'
(which is what it really is ) becomes 'security-administration' ... so I
added another bit in there to add 'update', 'delete', etc.
... looks much better.

I'll look into formatting in just a bit...

S. Stuart Smith

**Comment by kchapple** [comment]
Look s good. Usually I don't merge into our master until the PR comes back as part of the upstream code-base. It's easier to keep our master in sync that way. Next time, you can just leave your feature branch, and create an upstream PR from that. I'll go ahead and create PR into upstream and tag you.

**Comment by StuartSmith183** [comment]
D'oh ... dang ... I was in the middle of reviewing the PR and something was
tickling the back of my neck... and I guess that is what it was... going
local, instead of PRing against upstream.
(seems everyone does GIT just *a little* bit differently, and I've got all
those different ways running around in my brains).

Thanks for that, I'll make sure to do it that way in the future.

I've spent a little time on the new project, (not tons, holiday weekend and
all, ya know 🍔🍺🎆 ). But I'm getting familiar with where things are ...
learning where different data points are in the DB etc, and what they would
map to in the code/records.


S. Stuart Smith

**Pull request merged**
